### ISSUE TITLE
Ranking interpretation

### ISSUE THREAD

**Issue by nsankar** [FRANe-team/FRANe#8]
@urhprimozic 

Thanks for developing this great library using FRANe. When we tested the ranking on our dataset with about 40 metrics, some of the metric rankings have the same ranking. How to interpret it qualitatively? Is it correct to say that the metrics which have the same ranking score would have an equal importance (at a lower or higher level) ?

Thanks in advance

**Comment by Petkomat** [comment]
FRANe is applicable in the case when we have a tabular dataset, such as

```
x1,x2,x3,...,xN
10,33,82,...,70
11,32,88,...,90
13,33,87,...,80
...
...
```

Then FRANe can be used to compute the importance of the features (attributes) `x1`, `x2`, ..., `xN`.

If the features are what you are referring to as _metrics_, then your interpretation is correct! If two of them, say `x1` and `x3` have (approximately) the same score, they are (approximately) equally important.

If not, can you please explain what do you mean by metrics (and/ or maybe give an excerpt of your dataset)?

**Comment by nsankar** [comment]
@Petkomat Yes. I had meant feature attributes as the metrics. (I used this term because it is sensor related data !) . Also how do we relate and interpret what FRAN rankings of features from a Page rank perspective, if you can give a simple example, that would be great.  

For example, Lets say I have 3 sensor attributes viz. temperature, pressure and velocity and if pressure is ranked highest followed by velocity , while the temperature is ranked low, can we say that the relative influence of pressure and velocity on a measured system could be higher than temperature and velocity just as a case.?

Thank you.

**Comment by urhprimozic** [comment]
To follow you example, here is  a simple , made up dataset (*that probably doesn't exist in nature*), for which frane ranks features as written in your comment.
|pressure|velocity|temperature|
|-----------|----------------|----------|
|5|25|5|
|10|100|-3|
|2|4|16|
 |0|0|0|

```

x = np.array([[5, 25, 5], [10, 100, -3], [0, 0, 0]])
r = frane.FRANe()
r.fit(x)
scores = r.feature_importances_

>>> scores
array([0.48648649, 0.40824312, 0.1052704 ])
```
# Page Rank perspective
FRANe first calculates distances between the features:
```
array([[0.        , 0.03923108, 1.37115374],
       [0.03923108, 0.        , 1.61413236],
       [1.37115374, 1.61413236, 0.        ]])
```
Than it starts generating weighted graphs of features, gradually adding more edges. When we add all the edges with weights below ´1´, we get:
```dot
graph G {
preassure - velocity [weights =  0.03923108]
}
```
We run page rank on every graph generated, and pick the most interesting one for feature ranking. 
# General case
FRANe ranks features based on their Page Rank (centrality measure) on a graph of distances. The best ranked features are expected to be central features of a graph. Data shows that ranking, calculated using FRANe, is good. 

> can we say that the relative influence of pressure and velocity on a measured system could be higher than temperature and velocity just as a case.?

Yes, pressure and velocity are more important features.

**Comment by nsankar** [comment]
@urhprimozic  Got it. Thank you for answering the query and enlightening !
